# Welcome to Numpy Tutorial

In [1]:
import numpy as np


In [2]:
myarr = np.array([[1,2,37,4]])

In [3]:
int(myarr[0,1])

2

In [4]:
myarr1 = np.array([1,2,37,4])

In [5]:
int(myarr1[0])

1

In [6]:
int(myarr1[2])

37

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr1.shape

(4,)

In [9]:
myarr.dtype

dtype('int64')

In [10]:
myarr1.dtype

dtype('int64')

In [11]:
myarr[0,1]=40

In [12]:
myarr

array([[ 1, 40, 37,  4]])

# Array creation: Conversion from other Python structures

In [13]:
listmyarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
listmyarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listmyarray.shape

(3, 3)

In [16]:
listmyarray.size

9

In [17]:
listmyarray.dtype

dtype('int64')

In [18]:
zeros=np.zeros((2,6))

In [19]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
zero1=np.zeros((3,3))

In [21]:
zero1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
zeros.shape

(2, 6)

In [24]:
rng=np.arange(15)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
rng1=np.arange(50)

In [27]:
rng1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
lspace=np.linspace(1,5,12)

In [29]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [30]:
lspace1=np.linspace(1,50,20)

In [31]:
lspace1

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [32]:
lspace2=np.linspace(1,4,4)

In [33]:
lspace2

array([1., 2., 3., 4.])

In [34]:
emp=np.empty((4,6))

In [35]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.11261027e-306,
        1.95819401e-306, 1.11261502e-306, 1.42410974e-306]])

In [36]:
emp_like=np.empty_like(lspace)

In [37]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [38]:
ide=np.identity(45)

In [39]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
ide.shape

(45, 45)

In [41]:
ide.dtype

dtype('float64')

In [42]:
arr=np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr=arr.reshape(3,33)

In [45]:
div=np.arange(100)

In [46]:
div

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
div=div.reshape(10,10)

In [48]:
div

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
arr=arr.ravel()

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [51]:
arr.shape

(99,)

# AXIS

In [52]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [53]:
arr4=np.array(x)

In [54]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr4.sum(axis=0)

array([12, 15, 18])

In [56]:
arr4.sum(axis=1)

array([ 6, 15, 24])

In [57]:
arr4.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [58]:
arr4.flat

In [59]:
for item in arr4.flat:
    print(item)
    

1
2
3
4
5
6
7
8
9


In [60]:
arr4.ndim

2

In [61]:
arr4.size

9

In [62]:
arr4.nbytes

72

In [63]:
one=np.array([1,2,567,8])

In [64]:
int(one.argmax())

2

In [65]:
int(one.argmin())

0

In [66]:
one.argsort()

array([0, 1, 3, 2])

In [67]:
one

array([  1,   2, 567,   8])

In [68]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
int(arr4.argmin())

0

In [70]:
int(arr4.argmax())

8

In [71]:
arr4.argmax(axis=0)

array([2, 2, 2])

In [72]:
arr4.argmin(axis=1)

array([0, 0, 0])

In [73]:
a=[[2,6,1],[7,3,9],[1,9,4]]

In [74]:
y=np.array(a)

In [75]:
y

array([[2, 6, 1],
       [7, 3, 9],
       [1, 9, 4]])

In [76]:
int(y.argmax())

5

In [77]:
int(y.argmin())

2

In [78]:
y.argmax(axis=0)

array([1, 2, 1])

In [79]:
y.argmin(axis=0)

array([2, 1, 0])

In [80]:
y.argmax(axis=1)

array([1, 2, 1])

In [81]:
y.argmin(axis=1)

array([2, 1, 0])

In [82]:
y.argsort(axis=0)

array([[2, 1, 0],
       [0, 0, 2],
       [1, 2, 1]])

In [83]:
y.argsort(axis=1)

array([[2, 0, 1],
       [1, 0, 2],
       [0, 2, 1]])

In [84]:
y.reshape(9,1)

array([[2],
       [6],
       [1],
       [7],
       [3],
       [9],
       [1],
       [9],
       [4]])

In [85]:
y

array([[2, 6, 1],
       [7, 3, 9],
       [1, 9, 4]])

In [86]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr5=np.array([[1, 2, 3],
       [2, 5, 3],
       [1,4,3]])

In [88]:
arr5

array([[1, 2, 3],
       [2, 5, 3],
       [1, 4, 3]])

In [89]:
arr4 + arr5

array([[ 2,  4,  6],
       [ 6, 10,  9],
       [ 8, 12, 12]])

In [90]:
arr4 * arr5

array([[ 1,  4,  9],
       [ 8, 25, 18],
       [ 7, 32, 27]])

In [91]:
np.sqrt(arr4)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [92]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
np.where(arr4>7)

(array([2, 2]), array([1, 2]))

In [94]:
arrr=[[2,3,7],[5,6,9],[6,8,3]]

In [95]:
ab=np.array(arrr)

In [96]:
ab

array([[2, 3, 7],
       [5, 6, 9],
       [6, 8, 3]])

In [100]:
np.where(ab>7)

(array([1, 2]), array([2, 1]))

In [102]:
np.count_nonzero(arrr)

9